#Deploy the pod
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trader
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: trader
        version: v1
    spec:
      containers:
      - name: trader
        image: trader:latest
        ports:
          - containerPort: 9080
        imagePullPolicy: IfNotPresent
---
#Deploy the service
apiVersion: v1
kind: Service
metadata:
  name: trader-service
  labels:
    app: trader
spec:
  type: NodePort
  ports:
    - port: 9080
#     nodePort: 31000
  selector:
    app: trader
---   
#Configure the ingress 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
# annotations:
#   ingress.kubernetes.io/rewrite-target: /trader
  name: trader-ingress
spec:
  rules:
  - http:
      paths:
      - path: /trader
        backend:
          serviceName: trader-service
          servicePort: 9080
